# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [1]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [2]:
# Import torch
import torch

# Create random tensor
rand_tensor = torch.rand(size=(7, 7))
rand_tensor

tensor([[0.7882, 0.5285, 0.9045, 0.8878, 0.1846, 0.1335, 0.2913],
        [0.7061, 0.2663, 0.0265, 0.3459, 0.5625, 0.6955, 0.1478],
        [0.6004, 0.6839, 0.4936, 0.9336, 0.0506, 0.5933, 0.8086],
        [0.2548, 0.1865, 0.5651, 0.5934, 0.2483, 0.5924, 0.7420],
        [0.2823, 0.8940, 0.2740, 0.2884, 0.5090, 0.7887, 0.3355],
        [0.2315, 0.7038, 0.9390, 0.7816, 0.4503, 0.2612, 0.6642],
        [0.4778, 0.0302, 0.9302, 0.9335, 0.8037, 0.3050, 0.2641]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [3]:
# Create another random tensor
rand_tensor2 = torch.rand(size=(1, 7))
# Perform matrix multiplication (1, 7) @ (7, 7) -> (1, 7)
sol1 = rand_tensor2 @ rand_tensor
sol2 = torch.matmul(rand_tensor2, rand_tensor)
sol3 = torch.mm(rand_tensor2, rand_tensor)
print('Matrix multiplication with @ operator:      ', sol1)
print('Matrix multiplication with matmul function: ', sol2)
print('Matrix multiplication with mm function:     ', sol3)

Matrix multiplication with @ operator:       tensor([[1.9010, 2.3451, 2.3363, 2.6824, 1.8056, 2.2878, 2.0569]])
Matrix multiplication with matmul function:  tensor([[1.9010, 2.3451, 2.3363, 2.6824, 1.8056, 2.2878, 2.0569]])
Matrix multiplication with mm function:      tensor([[1.9010, 2.3451, 2.3363, 2.6824, 1.8056, 2.2878, 2.0569]])


### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [4]:
# Set manual seed
torch.manual_seed(0)

# Create two random tensors
a = torch.rand(size=(7, 7))
b = torch.rand(size=(1,7))

# Matrix multiply tensors
a @ b.T

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [5]:
# Set random seed on the GPU
if torch.cuda.is_available():
  torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [6]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
device = 'cuda' if torch.cuda.is_available() else 'cpu'
# Create two random tensors on GPU
a = torch.rand(size=(2, 3))
b = torch.rand(size=(2, 3))
a = a.to(device)
b = b.to(device)
print('Device:',device)
print(a)
print(b)

Device: cuda
tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0')
tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]], device='cuda:0')



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [7]:
# Perform matmul on tensor_A and tensor_B
a_matmul_b = a @ b.T
a_matmul_b, a_matmul_b.size()

(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'),
 torch.Size([2, 2]))

### 8. Find the maximum and minimum values of the output of 7.

In [8]:
# Find max
print('Max of [[0.3647, 0.4709],[0.5184, 0.5617]] is', a_matmul_b.max())
# Find min
print('Min of [[0.3647, 0.4709],[0.5184, 0.5617]] is', a_matmul_b.min())

Max of [[0.3647, 0.4709],[0.5184, 0.5617]] is tensor(0.5617, device='cuda:0')
Min of [[0.3647, 0.4709],[0.5184, 0.5617]] is tensor(0.3647, device='cuda:0')


### 9. Find the maximum and minimum index values of the output of 7.

In [9]:
# Find arg max
print('ArgMax of [[0.3647, 0.4709],[0.5184, 0.5617]] is', a_matmul_b.argmax())

# Find arg min
print('ArgMin of [[0.3647, 0.4709],[0.5184, 0.5617]] is', a_matmul_b.argmin())

ArgMax of [[0.3647, 0.4709],[0.5184, 0.5617]] is tensor(3, device='cuda:0')
ArgMin of [[0.3647, 0.4709],[0.5184, 0.5617]] is tensor(0, device='cuda:0')



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [16]:
# Set seed
torch.manual_seed(7)

# Create random tensor
c = torch.rand(size=(1, 1, 1, 10))

# Remove single dimensions
squeezed_c = torch.squeeze(c)
# Print out tensors and their shapes
print(c, c.size())
print(squeezed_c, squeezed_c.size())

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
